---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-frontend
  template:
    metadata:
      labels:
        app: demo-frontend
    spec:
      containers:
        - name: demo-frontend
          image: 200378773816.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend:latest1212
          imagePullPolicy: Always
          ports:
            - containerPort: 80